### ISSUE TITLE
Learnings > Build with BodilessJS

### ISSUE THREAD

**Issue by alexvanyo** [hvanyo/solutionsbyheidi#1]
https://github.com/hvanyo/solutionsbyheidi/blob/dffba7aa13216b8cfb7587c76019d25d9a15f0ee/src/data/pages/learnings/sitebuiltwithBodilessJS/page%246a112b20-3819-11eb-86c1-91e6b00020c6.json#L82

Seems a little awkward, maybe something like this?

> This is directly deployed on hosting/internet, with the benefits of improved performance and security compared to traditional CMS systems.

**Comment by hvanyo** [comment]
Addressed
