### ISSUE TITLE
Learnings > Built with BodilessJS > Hosting a Static Site

### ISSUE THREAD

**Issue by alexvanyo** [hvanyo/solutionsbyheidi#2]
https://github.com/hvanyo/solutionsbyheidi/blob/dffba7aa13216b8cfb7587c76019d25d9a15f0ee/src/data/pages/learnings/sitebuiltwithBodilessJS/page%247be28f90-381b-11eb-84cb-c32a7e5d05e9.json#L82

> Since the technically
Seems to be missing a word

Also looks like there are a bunch of extra spaces after sentences.

**Comment by hvanyo** [comment]
Addressed
