### ISSUE TITLE
Learnings > Built with BodilessJS -> Technology behind BodilessJS

### ISSUE THREAD

**Issue by alexvanyo** [hvanyo/solutionsbyheidi#3]
https://github.com/hvanyo/solutionsbyheidi/blob/dffba7aa13216b8cfb7587c76019d25d9a15f0ee/src/data/pages/learnings/sitebuiltwithBodilessJS/page%24da9b94b0-3815-11eb-86c1-91e6b00020c6.json#L148

`JAMSTACK` here is all uppercased, which differs from the top paragraph.

**Comment by hvanyo** [comment]
addressed
