### ISSUE TITLE
FeatureBlocks > Implementation

### ISSUE THREAD

**Issue by alexvanyo** [hvanyo/solutionsbyheidi#4]
https://github.com/hvanyo/solutionsbyheidi/blob/dffba7aa13216b8cfb7587c76019d25d9a15f0ee/src/data/pages/FeatureBlocksFlowContainer%2430d56b90-3770-11eb-96a3-790e7fbfc0e0%24body.json#L16

The `Implementation` and `Gather & Define Requirements` don't have periods at the end, but the rest do.

**Comment by hvanyo** [comment]
Addressed
