### ISSUE TITLE
FeatureBlocks > Launch & LifeCycle support

### ISSUE THREAD

**Issue by alexvanyo** [hvanyo/solutionsbyheidi#6]
https://github.com/hvanyo/solutionsbyheidi/blob/dffba7aa13216b8cfb7587c76019d25d9a15f0ee/src/data/pages/FeatureBlocksFlowContainer%24335dc420-3770-11eb-96a3-790e7fbfc0e0%24image.json#L3

The `alt` text has a weird casing. I feel like I've usually just seen `Lifecycle` as one word without `c` capitalized.

**Comment by hvanyo** [comment]
Addressed
