### ISSUE TITLE
FeatureBlocks > Design a Technical Solution

### ISSUE THREAD

**Issue by alexvanyo** [hvanyo/solutionsbyheidi#7]
https://github.com/hvanyo/solutionsbyheidi/blob/dffba7aa13216b8cfb7587c76019d25d9a15f0ee/src/data/pages/FeatureBlocksFlowContainer%24d739ed00-376e-11eb-bcb8-5fcffa3f000f%24body.json#L16

Typo: `artitects` > `architects`

**Comment by hvanyo** [comment]
Addressed
