### ISSUE TITLE
MainPage > Solutions Offered

### ISSUE THREAD

**Issue by alexvanyo** [hvanyo/solutionsbyheidi#8]
https://github.com/hvanyo/solutionsbyheidi/blob/dffba7aa13216b8cfb7587c76019d25d9a15f0ee/src/data/pages/feature_sectionsummary.json#L16

It feels a little weird to me that

> My priority is to provide best quality services to my clients.

comes underneath the `Solutions Offered` header, in between `Solutions Offered` and the list of solutions offered.

**Comment by hvanyo** [comment]
Addressed change to "combining multiple roles into technical oversight of a project"
